/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const BattleStartLazyImport = createFileRoute('/battle/start')()
const BattleSelectLazyImport = createFileRoute('/battle/select')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BattleStartLazyRoute = BattleStartLazyImport.update({
  path: '/battle/start',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/battle/start.lazy').then((d) => d.Route))

const BattleSelectLazyRoute = BattleSelectLazyImport.update({
  path: '/battle/select',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/battle/select.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/battle/select': {
      preLoaderRoute: typeof BattleSelectLazyImport
      parentRoute: typeof rootRoute
    }
    '/battle/start': {
      preLoaderRoute: typeof BattleStartLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BattleSelectLazyRoute,
  BattleStartLazyRoute,
])

/* prettier-ignore-end */
