/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BattleLazyImport = createFileRoute('/Battle')()
const BattleSelectLazyImport = createFileRoute('/battle/select')()

// Create/Update Routes

const BattleLazyRoute = BattleLazyImport.update({
  path: '/Battle',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Battle.lazy').then((d) => d.Route))

const BattleSelectLazyRoute = BattleSelectLazyImport.update({
  path: '/battle/select',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/battle/select.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Battle': {
      preLoaderRoute: typeof BattleLazyImport
      parentRoute: typeof rootRoute
    }
    '/battle/select': {
      preLoaderRoute: typeof BattleSelectLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  BattleLazyRoute,
  BattleSelectLazyRoute,
])

/* prettier-ignore-end */
